[package]
name = "ntfy"
version = "0.7.0"
edition = "2021"
description = "Library for sending notifications over ntfy"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/shadowylab/ntfy"
repository = "https://github.com/shadowylab/ntfy.git"
readme = "README.md"
keywords = ["ntfy", "notifications", "sdk"]

[features]
default = ["async"]
async = ["dep:reqwest"]
blocking = ["dep:ureq"]

[dependencies]
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "3.0", features = ["json", "socks-proxy"], optional = true }
url = { version = "2", features = ["serde"] }
http = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "blocking"
required-features = ["blocking"]

[[example]]
name = "client"
required-features = ["async"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
