[package]
name = "ntfy"
version = "0.7.0"
edition = "2021"
description = "Library for sending notifications over ntfy"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/shadowylab/ntfy"
repository = "https://github.com/shadowylab/ntfy.git"
readme = "README.md"
keywords = ["ntfy", "notifications", "sdk"]

[features]
# Default features
default = ["async", "rustls"]
# Enables the async client
async = ["dep:reqwest"]
# Enables the blocking client
blocking = ["dep:ureq"]
# Enables socks proxy support
socks = ["reqwest?/socks", "ureq?/socks-proxy"]
# Enables rust TLS
rustls = ["reqwest?/rustls-tls-webpki-roots", "ureq?/rustls"]
# Enables native TLS (openssl)
native-tls = ["reqwest?/native-tls", "ureq?/native-tls"]

[dependencies]
base64 = "0.22"
http = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["json"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "3.0", default-features = false , features = ["json"], optional = true }
url = { version = "2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "blocking"
required-features = ["blocking", "socks"]

[[example]]
name = "client"
required-features = ["async", "socks"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
